### ISSUE TITLE
可视化图片的理解

### ISSUE THREAD

**Issue by Elaineok** [NUST-Machine-Intelligence-Laboratory/nsrom#1]
![image](https://user-images.githubusercontent.com/46559128/126036752-d0b2cd92-5da4-4311-8a9b-31d916cdde72.png)
你好，感谢你对弱监督语义分割做的贡献，我对可视化图片中的白色区域指代什么不是很清楚，想请教一下。谢谢

**Comment by XingxingW** [comment]
> ![image](https://user-images.githubusercontent.com/46559128/126036752-d0b2cd92-5da4-4311-8a9b-31d916cdde72.png)
> 你好，感谢你对弱监督语义分割做的贡献，我对可视化图片中的白色区域指代什么不是很清楚，想请教一下。谢谢

白色区域是类别无法确定的区域，在分割网络训练时，loss计算不考虑这些像素
