### ISSUE TITLE
test问题

### ISSUE THREAD

**Issue by cny1234** [NUST-Machine-Intelligence-Laboratory/nsrom#10]
生成伪标签的时候需要saliancy_aug做背景提取，但saliancy_aug里只包含了train图片的显著图，测试的时候 使用val图片，但没有办法生成val图片的伪标签和遮挡伪标签，怎么测试呢？

**Comment by chentao2016** [comment]
伪标签仅用于训练阶段。测试的时候，输入图片就能得到分割结果，不需要生成伪标签和遮挡伪标签。

**Comment by cny1234** [comment]
测试用的是voc2012原图就可以对吗

**Comment by chentao2016** [comment]
对的，不需要其它特殊处理。图片列表见https://github.com/NUST-Machine-Intelligence-Laboratory/nsrom/blob/main/segmentation/list/val.txt 或 https://github.com/NUST-Machine-Intelligence-Laboratory/nsrom/blob/main/segmentation/list/test.txt

**Comment by cny1234** [comment]
好的，明白，谢谢解答！
