### ISSUE TITLE
用伪标签训练模型

### ISSUE THREAD

**Issue by cny1234** [NUST-Machine-Intelligence-Laboratory/nsrom#11]
> 你好，用伪标签训练模型的时候代码里好像没有设置伪标签的路径，是用的图中注释掉的代码吗？
![image](https://user-images.githubusercontent.com/115700129/202100072-17233fc5-56be-42fc-80b5-91a9f050d409.png)

**Comment by chentao2016** [comment]
是的，改下路径即可

**Comment by cny1234** [comment]
明白，感谢解答
