### ISSUE TITLE
背景阈值的修改对最后模型的测试会有影响吗？

### ISSUE THREAD

**Issue by cny1234** [NUST-Machine-Intelligence-Laboratory/nsrom#13]
我尝试修改背景阈值0.3，改了之后伪标签对比论文代码原来的伪标签有差别，但是对于最后的模型测试结果没有变化，还是70.4%，不太明白这是为什么呢？

**Comment by chentao2016** [comment]
这是训练的不稳定性导致的，你用同样的标签训练分割模型也会得到不同的结果。一般需要多次训练看平均的趋势。
