### ISSUE TITLE
分类网络和生成伪标签改变对模型测试会有影响吗

### ISSUE THREAD

**Issue by cny1234** [NUST-Machine-Intelligence-Laboratory/nsrom#14]
我用了一个别的分类网络生成伪标签去训练nsrom的分割网络，伪标签和nsrom原来的分类网络生成的伪标签是能明显看出差别的，但最终测试结果还是原来的70.4%，我有点疑惑这是为什么呢？

**Comment by chentao2016** [comment]
会有影响，而且影响极大。是不是用错pth文件了？注意替换成你们自己训练得到结果的路径，或者贴一下每个类别的iou，帮你看一下
