### ISSUE TITLE
test数据集图片怎么评估

### ISSUE THREAD

**Issue by cny1234** [NUST-Machine-Intelligence-Laboratory/nsrom#15]
你好，我想评估一下数据集的test性能，但总是提示label的问题。所以导致没有预测结果。我想问一下是训练好之后是怎么预测测试集结果的呢？

**Comment by chentao2016** [comment]
VOC测试集没有公开，得到预测结果后需要上传到官方网站进行测试：http://host.robots.ox.ac.uk:8080/

**Comment by cny1234** [comment]
能麻烦告诉我一下预测的过程吗&nbsp; 我用训练过的模型预测&nbsp; &nbsp;没得到任何文件&nbsp; 想确认一下是不是我的操作步骤就有问题。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月25日(周六) 晚上9:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [NUST-Machine-Intelligence-Laboratory/nsrom] test数据集图片怎么评估 (Issue #15)




 
VOC测试集没有公开，得到预测结果后需要上传到官方网站进行测试：http://host.robots.ox.ac.uk:8080/

**Comment by chentao2016** [comment]
crf之后将预测结果保存成图片即可。留个微信，我加你。

**Comment by cny1234** [comment]
xwcwymdxls&nbsp; &nbsp;我的微信号&nbsp; 谢谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月25日(周六) 晚上9:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [NUST-Machine-Intelligence-Laboratory/nsrom] test数据集图片怎么评估 (Issue #15)




 
crf之后将预测结果保存成图片即可。留个微信，我加你。
