### ISSUE TITLE
baseline是哪个模型呢

### ISSUE THREAD

**Issue by cny1234** [NUST-Machine-Intelligence-Laboratory/nsrom#16]
我看到论文中做各个模块的消融，我好像没有在论文里看到具体是以哪个模型代码做的baseline呢

**Comment by chentao2016** [comment]
把论文提出的模块去掉就是baseline，是基于OAA模型的改进的：https://github.com/PengtaoJiang/OAA-PyTorch。建议在最新的CVPR22和23的文章上做改进，从而得到更SOTA结果。
