### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (366,500) (3,)

### ISSUE THREAD

**Issue by xiexua** [NUST-Machine-Intelligence-Laboratory/nsrom#3]
您好，我运行第一条指令“python main.py test --config-path configs/voc12.yaml --model-path data/models/checkpoint_70.4.pth”的时候会出现这个问题，请问您那边也有这种情况吗？可以怎么解决呢？
![图片](https://user-images.githubusercontent.com/89509450/130742472-cae3aff0-d70a-4fd4-a566-08470a0bbf7d.png)

**Comment by chentao2016** [comment]
The segmentation code is borrowed from this popular project: https://github.com/kazuto1011/deeplab-pytorch. Please check whether you can run their evaluation code.
