### ISSUE TITLE
problem about GCN

### ISSUE THREAD

**Issue by YuYue26** [NUST-Machine-Intelligence-Laboratory/nsrom#5]
![Screenshot from 2022-01-14 17-07-55](https://user-images.githubusercontent.com/86346611/149489261-a3aa726a-e9d9-422c-abca-a1a1d2e454ec.png)

**I can't find the I, Ag and Wg in this code, only some convs exist in follow code**

![Screenshot from 2022-01-14 17-10-18](https://user-images.githubusercontent.com/86346611/149489510-da0b95be-b9ee-4e57-9e08-684903b7548d.png)

please help child!!! how the GCN works?

**Comment by chentao2016** [comment]
According to my understanding, -self.conv1 is Ag and self.conv2 is Wg.  For h = h+x, x= IV=V.
