### ISSUE TITLE
关于GloRe unit的一些疑问

### ISSUE THREAD

**Issue by mymuli** [NUST-Machine-Intelligence-Laboratory/nsrom#6]
关于GloRe unit，我想请教几个问题:
**Q1: 在Vgg.py文件里面，发现只使用了单层的GloRe unit...想问一下，你们在WSSS任务里面有测试2层/3层的效果呢？**
https://github.com/NUST-Machine-Intelligence-Laboratory/nsrom/blob/fa052867c1d09eb6008ba74b4dc7f8e8fceb93d4/classification/models/vgg.py#L27

**Q2: 如果使用ResNet-101作为backbone(448x448图像作为输入), 则最后卷积层输出的特征图大小为14x14x2048。根据GloRe原文，按照“1/4”原则，在GloRe unit里面，通道数减为512...**
![1](https://user-images.githubusercontent.com/37521721/161186300-4714308c-4399-4bce-a744-e0b967142c70.png)

**与此同时，根据代码，GCN中的节点数为256. 可是，特征图的像素点数为14x14=196.  节点数256>像素点数196，感觉违背视觉原则。** 
**想问一下，如果使用ResNet-101作为backbone(448x448图像作为输入)，你们会怎么处理这一问题呢？**
https://github.com/NUST-Machine-Intelligence-Laboratory/nsrom/blob/fa052867c1d09eb6008ba74b4dc7f8e8fceb93d4/classification/models/global_reasoning_unit.py#L29

**Comment by chentao2016** [comment]
Q1：GloRe unit原文里提到单层的GloRe unit效果比两层更好，因此当时做的时候只用了单层，并没有测试过2层/3层的效果。

Q2：GCN的目的是为了捕获全局信息，在GCN背后的原理是有效的情况下，不必纠结节点数256>像素点数196的问题，深度学习一般都需要调参，得多试节点数，例如128，96；另外可以将stride=32改为16，从而获得更大分辨率的特征图。

**Comment by mymuli** [comment]
好的，感谢回复！
