### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'astype'

### ISSUE THREAD

**Issue by cny1234** [NUST-Machine-Intelligence-Laboratory/nsrom#8]
你好，我运行第一条指令python main.py test --config-path configs/voc12.yaml --model-path data/models/checkpoint_70.4.pth
时一直报这个错AttributeError: 'NoneType' object has no attribute 'astype'，差了很多资料，但没解决，能帮忙看看吗
![image](https://user-images.githubusercontent.com/115700129/195584558-960498ca-849f-424d-814e-289416de7811.png)

**Comment by chentao2016** [comment]
应该是图片路径问题，你的报错信息已经提示了
![image](https://user-images.githubusercontent.com/24662937/195743891-554ef1ad-3f63-4e25-b179-c5b9be792508.png)
