### ISSUE TITLE
SegmentationClassAug和SegmentationClass是一样的吗

### ISSUE THREAD

**Issue by cny1234** [NUST-Machine-Intelligence-Laboratory/nsrom#9]
![image](https://user-images.githubusercontent.com/115700129/196953172-ff7b7f7a-e56a-49ca-b168-a0159c973776.png)
我这个里面是是数据集里没有SegmentationClassAug文件报的错，但我不确定SegmentationClassAug是什么图片

**Comment by chentao2016** [comment]
[train_cls.txt](https://github.com/NUST-Machine-Intelligence-Laboratory/nsrom/blob/main/classification/data/train_cls.txt)需要的是这个文件对应的图片，二者不一样

**Comment by cny1234** [comment]
那SegmentationClassAug的文件是在哪弄的，VOC数据集里只有SegmentationClass的图片,是不是分类训练得到的attention里面就是SegmentationClassAug的文件

**Comment by chentao2016** [comment]
![image](https://user-images.githubusercontent.com/24662937/197387630-bec06445-b204-4e12-a0f8-8e66bc05dd8e.png)文件可直接从https://github.com/Lixy1997/Group-WSSS这个项目提供的链接下载https://drive.google.com/file/d/1uh5bWXvLOpE-WZUUtO77uwCB4Qnh6d7X/view
